[package]
name = "bolthash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bolt_hash = { path = "../rust" }
atty = "0.2.14"

